language: node_js
node_js:
- node
- 4.0.0
deploy:
  provider: npm
  api_key:
    secure: E+UHhaPxurbySkVCvhw23pdHJx2FXxV63jW9wI6uud5S4YjFiPQWqNsXfwdt2oJyKNUtJp5JOwXy0rR4Ic/ShrQM3Ucogp1xpnFvJgiXdTUU+E+dYz//1KX6LkfGjfEcNiKvOLs2gAm7qvLpjpDg1xc5zFgfi6m1lfGv2vKrjRLbtXqKsMm5Be3mWncwS3YpMlMlirEF7Zj1Xlt3WXNZHk1mGsQUbEBmGX1hKoz1vQZ0jyueHnYFHobTmwwK9hy3/GtXCrn1JQTJBAQvdX+AGZOYq7FrdK/w9PgawQ6z35PLEaEzksXIdRxfx45TqmuP0u1rgfOSL8+3m5xfXzlc62AKqUUVHbgvkUpEODQrakmm4mO7xo0+nyLcS2tlUk4arkz4NlUZcFIRgbaXlDKIgGl3o+EQJPMF2nl4XAPeJ3Mdpp6Wvz8rIEdPlNLQr6IxCPt0Ty77z1MZ+lbgi3fo2/H/wCCT/3nbZLeaKNErygZGGz9ooJlDT30QNvHJtZY1B6WFHBCwsJBHJ0SbWnD3QA1TZklOX5V7o8503jiuqjbRVh6MOMX13VOg4LCT7lc0VDCn9rIAlq0D3BAK5nlv6wwmVfc3yQbv36nJDQLOyKitJYzLaPFCqRtevzsBMJOIKOts4kRcLAtz+QYiLDGlp40i3lp58DhJEg7140YtTDY=
  on:
    tags: true